### ISSUE TITLE
Works with AdGuard and blocking actual shorts

### ISSUE THREAD

**Issue by pascal1888** [gijsdev/ublock-hide-yt-shorts#24]
Hi! First of all, thanks a lot for creating this!!!

I use AdGuard, and adding the link to the raw .txt file works flawlessly. It seems that blocking youtube.com/shorts* works as well. Is there any particular reason why you do not include it in your file? Possibly because you would like to open shorts that are sent to you?

https://raw.githubusercontent.com/pascal1888/hide-yt-shorts-test/main/list.txt

Again, thanks a lot!

**Comment by gijsdev** [comment]
Yes, when someone send me a Short I still want to be able to see the video. I created this filterlist because I found it annoying that YouTube kept spamming my feeds full of Shorts, even though I never clicked on any of them.
I don't want to break functionality, I just want a feed of videos I might want to watch.

**Comment by pascal1888** [comment]
Fair enough. Thank you again!
